# -*- coding: utf-8 -*-
"""Table 10 (tab:hvg_sampler_axis): ways of meeting a request on one CRN generator.

Purity is the v8 lineage-ruler mean recorded per paper cell in 215_paper_numbers_v8.json; the
distance columns are averaged over that cell's own run stems, looked up in the scored artefacts.
The dagger row retrains the generator with a label embedding and is reported as a reference.
Three sampling seeds per arm; the table prints means only, as in the paper.

    python scripts/reproduce/table_10_sampler_axis.py
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (SCORED_FILES, TYPES, cell, emit, group_header,                # noqa: E402
                     over_stems, paper_rows, stem_index)

COLS = [("purity", 3), ("W1", 3), ("mmd2_rbf_biased", 4), ("pcc", 3)]


def tidy(row: str) -> str:
    r = row.replace("times", r"\times").replace("gamma=", r"\gamma=")
    r = r.replace("^{dagger", r"$^{\dagger}$").replace("{", "").replace("}", "")
    if r.startswith("Best-of-N"):
        n = r.split(",")[-1].strip()
        return f"Best-of-$N$, ${n}$"
    if r.startswith("Value-guided"):
        g = r.split("=")[-1].strip()
        return f"Value-guided, $\\gamma={g}$"
    if "fine-tuned" in r:
        return r"\textbf{Ours (fine-tuned)}$^{\dagger}$"
    if "frozen" in r:
        return r"\textbf{Ours (frozen generator)}"
    return r


def main() -> int:
    idx = stem_index(SCORED_FILES)
    rows = [r for r in paper_rows()["rows"] if r["table"] == "tab:hvg_sampler_axis"]
    order, seen = [], set()
    for r in rows:
        if r["row"] not in seen:
            seen.add(r["row"]); order.append(r["row"])
    lines = [r"% Table 10 -- generated by scripts/reproduce/table_10_sampler_axis.py",
             r"\begin{tabular}{l cccc}", r"\toprule",
             r"Conditioning & Purity $\uparrow$ & $W_1$ $\downarrow$ & MMD$^2$ $\downarrow$ & PCC $\uparrow$ \\"]
    for t in TYPES:
        lines += [r"\midrule", group_header(t, 5)]
        for name in order:
            r = next((x for x in rows if x["row"] == name and x["request"] == t), None)
            if r is None:
                continue
            cells = [cell(r["mean"], None, 3, with_sd=False)]
            for k, d in COLS[1:]:
                m, s, _ = over_stems(idx, r["stems"], k)
                cells.append(cell(m, None, d, with_sd=False))
            lines.append(f"{tidy(name)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_10_sampler_axis.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
