# -*- coding: utf-8 -*-
"""Table 8 (tab:hvg_tau): the product-tilt tempering exponent tau, one generator, three seeds.

Same construction as Table 6: purity from the audited per-cell record, distances averaged over
that cell's run stems.

    python scripts/reproduce/table_08_tilt_exponent.py
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (SCORED_FILES, TYPES, cell, emit, group_header,                # noqa: E402
                     over_stems, paper_rows, stem_index)

COLS = [("purity", 3), ("W1", 3), ("mmd2_rbf_biased", 4), ("pcc", 3)]


def main() -> int:
    idx = stem_index(SCORED_FILES)
    rows = [r for r in paper_rows()["rows"] if r["table"] == "tab:hvg_tau"]
    taus = sorted({r["row"] for r in rows}, key=float)
    lines = [r"% Table 8 -- generated by scripts/reproduce/table_08_tilt_exponent.py",
             r"\begin{tabular}{lcccc}", r"\toprule",
             r"$\tau$ & Purity $\uparrow$ & $W_1$ $\downarrow$ & MMD$^2$ $\downarrow$ & PCC $\uparrow$ \\"]
    for t in TYPES:
        lines += [r"\midrule", group_header(t, 5)]
        for tau in taus:
            r = next((x for x in rows if x["row"] == tau and x["request"] == t), None)
            if r is None:
                lines.append(f"${tau}$ & " + " & ".join(["MISSING"] * 4) + r" \\"); continue
            cells = [cell(r["mean"], r["sd"], 3)]
            for k, d in COLS[1:]:
                m, s, _ = over_stems(idx, r["stems"], k)
                cells.append(cell(m, s, d))
            lines.append(f"${tau}$ & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_08_tilt_exponent.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
