# -*- coding: utf-8 -*-
"""Table 3 (tab:hparams): the deployed sampler configuration.

Every value is read from crndiff/config.py, which is the single place the samplers read them
from, so this table cannot drift from what the code actually runs. n_out and the particle count
follow the recorded rule rather than being listed per request: N = max(2500, matched n of the
distance ruler) and M = 2N.

    python scripts/reproduce/table_03_hyperparameters.py
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from crndiff import config as C                                                    # noqa: E402
from _common import emit                                                           # noqa: E402

TAU = {"Endothelial": 0.4, "Myeloid": 0.2, "Neuronal": 0.2}


def main() -> int:
    matched = C.matched_n()
    rows = [
        ("Reverse steps $K$", f"{C.DEFAULT_K}"),
        ("Twist candidates per particle per step $J$", f"{C.DEFAULT_J}"),
        ("Reward exponent $\\alpha$", "1"),
        ("Resampling checkpoint interval", f"{C.DEFAULT_INTERVAL}"),
        ("ESS resampling threshold $\\vartheta$", f"{C.DEFAULT_ESS_FRAC}"),
        ("Minimum gap between events", f"{C.DEFAULT_MIN_RESAMPLE_GAP}"),
        ("Reward floor", f"${C.DEFAULT_REWARD_FLOOR:g}$"),
        ("Cell chunk (fixes the RNG consumption order)", f"{C.DEFAULT_CELL_CHUNK}"),
        ("Delivered cells $n_{\\mathrm{out}}$",
         "$\\max(%d, n_{\\mathrm{matched}})$" % C.DEPLOYED_N_FLOOR),
        ("Particles $M$", "$2\\,n_{\\mathrm{out}}$"),
    ]
    lines = [r"% Table 3 -- generated by scripts/reproduce/table_03_hyperparameters.py",
             r"% every value is read from crndiff/config.py at run time",
             r"\begin{tabular}{ll}", r"\toprule", r"Setting & Value \\", r"\midrule"]
    lines += [f"{k} & {v} \\\\" for k, v in rows]
    lines += [r"\midrule",
              r"\multicolumn{2}{l}{\emph{Per request}} \\",
              r"Request & $\tau$ \quad $n_{\mathrm{matched}}$ \quad $n_{\mathrm{out}}$ \quad $M$ \\"]
    for t, tau in TAU.items():
        n = C.n_out_for(t)
        lines.append(f"{t} & ${tau}$ \\quad ${matched.get(t, 0)}$ \\quad ${n}$ \\quad ${2*n}$ \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_03_hyperparameters.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
