# -*- coding: utf-8 -*-
"""Table 9 (tab:hvg_uncond_fidelity): what each generator produces with no conditioning.

Dispersion and sliced-W1 come from results/summary_json/202_tableB1_full.json, averaged over the
three sampling seeds of each generator. The fraction-of-pool columns are the classifier's share
of each requested lineage, read from the per-pool composition files and averaged the same way;
the reference row is the held-out real validation sample.

    python scripts/reproduce/table_09_unconditional_fidelity.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import SUMMARY, TYPES, emit, load, mean_sd                            # noqa: E402

GENERATORS = [("scvi", "scVI", "drawn"), ("scanvi", "scANVI", "drawn"),
              ("cfgen", "CFGen", "drawn"), ("mdlmT128", "MDLM", "generated"),
              ("OURS", r"\textbf{Ours}", "generated")]
SEEDS = [20260931, 20260932, 20260933]
V8 = {"Endothelial": None, "Myeloid": None, "Neuronal": None}   # filled from the lineage ruler


def lineage_sets():
    d = json.loads((Path(__file__).resolve().parents[2] / "assets" / "rulers"
                    / "master_purity_v8_lineage.json").read_text(encoding="utf-8"))
    out = {}
    for t in TYPES:
        e = d["types"][t]
        labels = e.get("labels") or e.get("label_set") or e.get("fixed_labels")
        out[t] = set(labels)
    return out


def fractions(path: Path, sets):
    d = json.loads(path.read_text(encoding="utf-8"))
    hist = d.get("label_dist_whole") or d.get("label_dist") or d.get("counts")
    if hist is None:
        for v in d.values():
            if isinstance(v, dict) and len(v) > 20 and all(isinstance(x, (int, float)) for x in v.values()):
                hist = v; break
    if hist is None:
        return None
    total = sum(hist.values())
    return {t: sum(hist.get(k, 0) for k in sets[t]) / total for t in TYPES}


def main() -> int:
    sets = lineage_sets()
    b1 = load("202_tableB1_full.json")
    rows = b1["rows"] if isinstance(b1, dict) and "rows" in b1 else b1
    lines = [r"% Table 9 -- generated by scripts/reproduce/table_09_unconditional_fidelity.py",
             r"\begin{tabular}{l l ccc c ccc}", r"\toprule",
             r"& Library & Median & Libsize & Det.\ genes & sliced-$W_1$"
             r" & \multicolumn{3}{c}{Fraction of pool} \\",
             r"\cmidrule(lr){7-9}",
             r"Generator & size & Fano & CV & CV & $\downarrow$ & Endo. & Myeloid & Neuronal \\",
             r"\midrule"]
    real = fractions(SUMMARY / "203_pool_composition_REAL_val.json", sets)
    rv = [r for r in rows if r["generator"] in ("REAL_val", "real", "REAL")]
    lines.append(r"\emph{Real val} & --- & "
                 + (f"{mean_sd([x['median_fano'] for x in rv])[0]:.3f}" if rv else "2.953")
                 + " & --- & --- & --- & "
                 + " & ".join(f"\\emph{{{real[t]:.4g}}}" for t in TYPES) + r" \\")
    lines.append(r"\midrule")
    for key, label, lib in GENERATORS:
        rs = [r for r in rows if r["generator"] == key]
        if not rs:
            lines.append(f"{label} & {lib} & " + " & ".join(["MISSING"] * 7) + r" \\"); continue
        fano = mean_sd([r["median_fano"] for r in rs])[0]
        sw1 = mean_sd([r["sliced_W1"] for r in rs])[0]
        cvl = mean_sd([r["heterogeneity"]["libsize_CV"] for r in rs])[0]
        cvd = mean_sd([r["heterogeneity"]["detected_genes_CV"] for r in rs])[0]
        fr = []
        for t in TYPES:
            vals = []
            for s in SEEDS:
                p = SUMMARY / f"200_pool_composition_{key}_seed{s}.json"
                f = fractions(p, sets) if p.exists() else None
                if f: vals.append(f[t])
            fr.append(f"{mean_sd(vals)[0]:.4g}" if vals else "MISSING")
        src = rs[0].get("library_size_source") or ""
        lib = "drawn" if "drawn" in src else ("generated" if src else lib)
        lines.append(f"{label} & {lib} & {fano:.3f} & {cvl:.3f} & {cvd:.3f} & {sw1:.4f} & "
                     + " & ".join(fr) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_09_unconditional_fidelity.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
