# -*- coding: utf-8 -*-
"""Table 7 (tab:hvg_sampling_cost): particle diagnostics for the two particle arms.

Resampling events and the pre-resampling ESS come from results/by_table/table07_particle_
diagnostics/<arm>/<request>__AGGREGATE.json (written by scripts/collect_ess_at_resampling.py).
Ancestry and uniqueness come from results/summary_json/ancestry_trace.json: ancestry is the
delivered-set ancestor fraction at the end of the reverse chain, uniqueness the same quantity
before any resampling has acted. Three sampling seeds per arm; sd is over those seeds.

    python scripts/reproduce/table_07_particle_diagnostics.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import BY_TABLE, TYPES, cell, emit, group_header, load                # noqa: E402

ARMS = [("Residual Correction", "fk_only", "FK steering"),
        ("OURS", "a1", r"\textbf{Tilted FK (ours)}")]


def main() -> int:
    anc = {(c["target"], c["arm"]): c["curves"] for c in load("ancestry_trace.json")["cells"]}
    lines = [r"% Table 7 -- generated by scripts/reproduce/table_07_particle_diagnostics.py",
             r"\begin{tabular}{lcccc}", r"\toprule",
             r"Sampler & Resampling events & Ancestry $\uparrow$ & Unique $\uparrow$ "
             r"& $\mathrm{ESS}_{\mathrm{pre}}/M$ $\uparrow$ \\"]
    for t in TYPES:
        lines += [r"\midrule", group_header(t, 5)]
        for folder, armkey, label in ARMS:
            p = BY_TABLE / "table07_particle_diagnostics" / folder / f"{t}__AGGREGATE.json"
            if not p.exists():
                lines.append(f"{label} & " + " & ".join(["MISSING"] * 4) + r" \\"); continue
            a = json.loads(p.read_text(encoding="utf-8"))["aggregate"]
            cu = anc.get((t, armkey))
            ancestry = (cu["anc_frac_delivered_mean"][-1], cu["anc_frac_delivered_sd"][-1]) if cu else (None, None)
            unique = (cu["anc_frac_delivered_mean"][0], cu["anc_frac_delivered_sd"][0]) if cu else (None, None)
            lines.append(f"{label} & "
                         + cell(a["n_events_mean"], a["n_events_sd"], 1) + " & "
                         + cell(*ancestry, 3) + " & " + cell(*unique, 3) + " & "
                         + cell(a["ess_pre_median_mean"], a["ess_pre_median_sd"], 3) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_07_particle_diagnostics.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
