# -*- coding: utf-8 -*-
"""Table 6 (tab:hvg_ablation): marginal tilt only / FK steering / tilted FK, one generator.

Purity is the v8 lineage-ruler mean and sd recorded per paper cell in 215_paper_numbers_v8.json;
the distance columns are averaged over that cell's own run stems, looked up in the scored
artefacts listed in _common.SCORED_FILES. Three sampling seeds per arm.

    python scripts/reproduce/table_06_ablation.py
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (SCORED_FILES, TYPES, cell, emit, group_header,                # noqa: E402
                     over_stems, paper_rows, stem_index)

LABEL = {"Marginal tilt only": "Marginal tilt only", "FK steering": "FK steering",
         "Tilted FK (ours)": r"\textbf{Tilted FK (ours)}"}
ORDER = ["Marginal tilt only", "FK steering", "Tilted FK (ours)"]
COLS = [("purity", 3, "max"), ("W1", 3, "min"), ("mmd2_rbf_biased", 4, "min"), ("pcc", 3, "max")]


def main() -> int:
    idx = stem_index(SCORED_FILES)
    rows = [r for r in paper_rows()["rows"] if r["table"] == "tab:hvg_ablation"]
    lines = [r"% Table 6 -- generated by scripts/reproduce/table_06_ablation.py",
             r"\begin{tabular}{lcccc}", r"\toprule",
             r"Sampler & Purity $\uparrow$ & $W_1$ $\downarrow$ & MMD$^2$ $\downarrow$ & PCC $\uparrow$ \\"]
    for t in TYPES:
        vals = {}
        for name in ORDER:
            r = next((x for x in rows if x["row"] == name and x["request"] == t), None)
            if r is None:
                vals[name] = {k: (None, None) for k, _, _ in COLS}; continue
            v = {"purity": (r["mean"], r["sd"])}
            for k, _, _ in COLS[1:]:
                m, s, n = over_stems(idx, r["stems"], k)
                v[k] = (m, s)
            vals[name] = v
        best = {}
        for k, _, how in COLS:
            xs = [vals[n][k][0] for n in ORDER if vals[n][k][0] is not None]
            best[k] = (max if how == "max" else min)(xs) if xs else None
        lines += [r"\midrule", group_header(t, 5)]
        for name in ORDER:
            cells = [cell(*vals[name][k], d, bold=(vals[name][k][0] == best[k])) for k, d, _ in COLS]
            lines.append(f"{LABEL[name]} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_06_ablation.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
