# -*- coding: utf-8 -*-
"""Table 2 (tab:hvg_single_type_main): conditional fidelity on three single-type requests.

Each generative arm is three training seeds with one sampling run each; the entries are the mean
and sample standard deviation (ddof=1) over those three runs. The per-run files are
results/table02_seeds/<arm>/<run>.json, written by the scoring pipeline and copied verbatim.
The real-cell row is the frozen v8 lineage purity ceiling plus the real-vs-real distances, both
read from results/summary_json/215_paper_numbers_v8.json.

    python scripts/reproduce/table_02_conditional_fidelity.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import SEEDS_T2, TYPES, emit, group_header, load, mean_sd            # noqa: E402

ARMS = ["scVI", "CFGen", "scANVI", "MDLM", "Ours"]
METRICS = [("purity_abs_v8", 3, "max"), ("W1", 3, "min"),
           ("mmd2", 4, "min"), ("pcc", 3, "max")]


def runs_of(arm):
    files = sorted((SEEDS_T2 / arm).glob("*.json"))
    if len(files) != 3:
        raise SystemExit(f"{arm}: expected 3 runs, found {len(files)} in {SEEDS_T2/arm}")
    return [json.loads(p.read_text(encoding="utf-8")) for p in files], [p.name for p in files]


def main() -> int:
    real = load("215_paper_numbers_v8.json")["real_cells"]
    lines = [r"% Table 2 -- generated by scripts/reproduce/table_02_conditional_fidelity.py",
             r"% three training seeds per arm, one sampling run each; mean +- sd (ddof=1)",
             r"\begin{tabular}{lcccc}", r"\toprule",
             r"Sampler & Purity $\uparrow$ & $W_1\downarrow$ & MMD$^2\downarrow$ & PCC $\uparrow$ \\"]
    for t in TYPES:
        stats = {}
        for arm in ARMS:
            ds, names = runs_of(arm)
            stats[arm] = {k: mean_sd([d["requests"][t][k] for d in ds]) for k, _, _ in METRICS}
            lines.append(f"% {t} / {arm}: " + ", ".join(names))
        best = {k: (max if how == "max" else min)(stats[a][k][0] for a in ARMS)
                for k, _, how in METRICS}
        lines += [r"\midrule", group_header(t, 5)]
        rv = real[t]
        lines.append("Real cells & " + " & ".join([
            f"${rv['purity_abs']:.3f}$", f"${rv['distances_unchanged']['W1']:.3f}$",
            f"${rv['distances_unchanged']['mmd2']:.4f}$",
            f"${rv['distances_unchanged']['pcc']:.3f}$"]) + r" \\")
        for arm in ARMS:
            cells = []
            for k, d, _ in METRICS:
                m, s = stats[arm][k]
                body = f"{m:.{d}f}_{{\\pm {s:.{d}f}}}"
                if m == best[k]:
                    body = r"\mathbf{" + body + "}"
                cells.append("$" + body + "$")
            name = r"\textbf{Ours}" if arm == "Ours" else arm
            lines.append(f"{name} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(lines, "table_02_conditional_fidelity.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
